module.exports = {
  "[来自剪藏] {title}": "[From Collections] {title}",
  "你需要重新加载该页面才能剪藏。请重新加载页面后再试一次": "You will need to reload the page to clip. Please reload the page and try again",
  "保存到": "Save to",
  "保存到语雀小记": "Save to Yuque Note",
  "保存失败，请重试！": "Failed to save, please try again!",
  "保存成功！": "Save success!",
  "其他": "Others",
  "划词剪藏默认保存位置": "The default save location of wordmark clipping",
  "划词快捷指令": "Word shortcut command",
  "剪藏": "Collections",
  "剪藏到": "clip to",
  "剪藏网址": "Clip url",
  "剪藏选取的内容": "Clip selected content",
  "升级新版本": "New version",
  "即将上新": "Coming soon",
  "去小记查看": "Go to Note",
  "小记": "Note",
  "打开语雀": "Open Yuque",
  "欢迎，请点击登录语雀账户": "Welcome",
  "登录失败": "登录失败",
  "登录验证": "登录验证",
  "知识库": "Knowledge base",
  "立即查看": "View now",
  "结果": "result",
  "继续选取": "Continue selecting",
  "访问主页": "Visit homepage",
  "语雀剪藏": "Yuque clipping",
  "语雀插件": "Yuque plugin",
  "语雀浏览器插件": "Yuque browser plugin",
  "账户": "account",
  "退出登录": "Logout account",
  "退出账户": "Logout account",
  "选中文本时，展示划词快捷指令功能": "When the text is selected, the shortcut command function of word marking will be displayed",
  "选择剪藏方式": "Choose clipping method",
  "通用设置": "General settings",
  "问题反馈": "Feedback"
};
