module.exports = {
  "[来自剪藏] {title}": "[From Collections] {title}",
  "保存到": "Save to",
  "保存到语雀小记": "Save to Yuque Note",
  "保存失败": "Save failed",
  "保存成功": "Saved successfully",
  "其他": "Others",
  "剪藏": "Collections",
  "升级新版本": "New version",
  "即将上新": "Coming soon",
  "去小记查看": "Go to Note",
  "多选剪藏": "Multi-select Clip",
  "小记": "Note",
  "整个页面(即将支持)": "All page",
  "欢迎，请点击登录语雀账户": "Welcome",
  "登录失败": "登录失败",
  "登录验证": "登录验证",
  "知识库": "Knowledge base",
  "立即查看": "View now",
  "继续选取": "Continue selecting",
  "访问主页": "Visit homepage",
  "语雀插件": "Yuque plugin",
  "请填写内容": "Please fill in the content",
  "退出账户": "Logout account",
  "链接剪藏": "Link Clip",
  "问题反馈": "Feedback"
};
