export const parsePageConfig = [
  {
    url: 'https?:\\/\\/www\\.toutiao\\.com\\/w\\/([a-zA-Z]\\/)?[a-zA-Z]\\d{10,}',
    include: ['.wtt-content'],
    exclude: [
      '.xgplayer',
      '#comment-area',
      '.content-action',
      '.author-info',
      '.article-content > h1',
      '.weitoutiao-content > h1',
      '.music-time',
    ],
  },
  {
    url: 'https?:\\/\\/www\\.toutiao\\.com\\/article',
    include: ['.article-content'],
    exclude: ['.xgplayer'],
  },
  {
    url: '^https?:\\/\\/www\\.toutiao\\.com\\/([a-zA-Z]\\/)?[a-zA-Z]\\d{10,}',
    include: ['.article-content', '.weitoutiao-content'],
    exclude: [
      '#comment-area',
      '.content-action',
      '.author-info',
      '.article-content > h1',
      '.weitoutiao-content > h1',
      'xg-mini-layer',
      'xg-center-grid',
      '.music-time',
    ],
  },
  {
    url: '^https?:\\/\\/zhuanlan\\.zhihu\\.com\\/p\\/',
    include: ['article.Post-Main'],
    exclude: ['.Post-Author', '.Post-topicsAndReviewer', '.RichContent-actions', 'img.LinkCard-image', '.Post-Header'],
  },
  {
    url: '^https?:\\/\\/www\\.zhihu\\.com\\/question\\/\\d+',
    include: ['.QuestionHeader-title', '.ContentItem.AnswerItem', '.List-item'],
    exclude: [
      '.ContentItem-time',
      '.ContentItem-actions',
      '.UserLink.AuthorInfo-avatarWrapper',
      '.ContentItem-expandButton',
      '.Voters',
      '.ModalWrap',
      '.ModalLoading-content',
      '.LinkCard-imageCell',
      '.QuestionInvitation',
      '.QuestionHeader-title',
    ],
  },
  {
    url: '^https?:\\/\\/mp\\.weixin\\.qq\\.com\\/s',
    include: ['.rich_media_wrp', '.js_inner', '#js_common_share_desc'],
    exclude: [
      '.weapp_text_link',
      'mp-miniprogram',
      '.weapp_display_element',
      'mpprofile',
      '#js_profile_qrcode_img',
      '#js_weapp_without_auth_weappurl',
      '.rich_media_title',
      '.js_video_play_controll',
      '.wx_video_play_opr',
      '.video_opr_sns',
      '.js_progress_bar',
      '.video_poster',
    ],
  },
  {
    url: '^https?:\\/\\/blog\\.csdn\\.net',
    include: ['.blog-content-box', '.hljs-comment'],
    exclude: [
      '.dp-highlighter.bg_cpp .bar',
      '.article-info-box',
      '#blogColumnPayAdvert',
      '#blogExtensionBox',
      '#blogVoteBox',
      '#treeSkill',
    ],
  },
  {
    url: '^https?:\\/\\/blog\\.csdn\\.net',
    include: ['.blog-content-box', '.hljs-comment'],
    exclude: ['.dp-highlighter.bg_cpp .bar'],
  },
  { url: '^https?:\\/\\/new\\.qq\\.com', include: ['.content-article'], exclude: ['.videoPlayerWrap'] },
  { url: '^https?:\\/\\/applet-data\\.web\\.bytedance\\.net', include: ['.app-main'], exclude: [] },
  { url: '^https?:\\/\\/blog\\.whatsapp\\.com', include: ['._9t2d'], exclude: [] },
  {
    url: '^https?:\\/\\/gist\\.github\\.com',
    include: ['.js-gist-file-update-container'],
    exclude: ['.px-0'],
  },
  {
    url: '^https?:\\/\\/www\\.lennysnewsletter\\.com\\/p',
    include: ['.single-post-container', '.header-with-anchor-widget', 'h1', 'h2', 'h3', 'h4'],
    exclude: [
      '.meta-subheader',
      '.share-dialog-title',
      '.social-preview-box',
      '.share-action-row',
      '.paywall',
      '.post-footer',
      '.comments-section',
      '.single-post-section',
      '.subscribe-footer',
      '.sideBySideWrap',
      '.tw-select-none',
      '.post-subheader',
      '.post-contributor-footer',
    ],
  },
  {
    url: '^https?:\\/\\/www\\.larksuite\\.com\\/hc\\/',
    include: ['#js-hc-breadcrumb  ~ div'],
    exclude: ['.image-wrapper-sizer'],
  },
  {
    url: '^https?:\\/\\/www\\.feishu\\.cn\\/hc\\/',
    include: ['#js-hc-breadcrumb ~ div'],
    exclude: ['.image-wrapper-sizer'],
  },
  {
    url: '^https?:\\/\\/baijiahao\\.baidu\\.com\\/s',
    include: ['#app > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)'],
    exclude: ['div > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)', '#commentModule'],
  },
  {
    url: '^https?:\\/\\/mbd\\.baidu\\.com\\/newspage\\/data\\/landingsuper?',
    include: ['#app > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)'],
    exclude: ['div > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)', '#commentModule'],
  },
  {
    url: '^https?:\\/\\/www\\.cnbc\\.com\\/\\d+\\/',
    include: ['.PageBuilder-pageWrapper'],
    exclude: [
      '.ArticleHeader-headerContentContainer',
      '.WatchLiveRightRail-rightRail',
      '#taboolaContainerMix',
      '.WatchLiveRightRail-inline',
      '.RegularArticle-ArticleHeader-2',
      '.JumpLink-container',
      '.CNBCGlobalNav-container',
      '.nav-menu-navLinks',
      '.RelatedContent-relatedContent',
      '.InlineVideo-videoFooter',
      '.PlayButton-featured',
      '.SocialShare-socialShare',
      '.LiveBlogHeader-timestampAndShareBarContainer',
    ],
  },
  {
    url: '^https?:\\/\\/nypost\\.com\\/\\d+\\/',
    include: ['.single--article'],
    exclude: [
      '.sharedaddy',
      '.author-flyout__inner',
      '.modal__email-author',
      '.zergnet-widget',
      '.circular-widget',
      '.single__sidebar',
      '.single__footer',
      '.vjs-control-bar',
      '.inline-module__inner',
      '.membership-reactions-module',
    ],
  },
  {
    url: '^https?:\\/\\/time\\.geekbang\\.org\\/column\\/article\\/',
    include: ['.Index_contentWidth_3_1Sf'],
    exclude: [
      '.recommend-read',
      '.Index_comment_1Pwfq',
      '.Index_comments_3HIaO',
      '.noteDialog_noteDialog_2w-W2',
      '.ArticleBottomBuyTipPC_unavailable_Cb50J',
      '.noteMenu_noteMenu_zbKHG',
      '.GkPlayer_controlWrap_g2M_1',
      '.AudioPlayerPC_left_1jNLt',
      '.ArticleLikeModulePc_LikeWrapper_HqHD5',
      '.AudioPlayerPC_icon_JtBkd',
    ],
  },
  {
    url: '^https?:\\/\\/dariusforoux\\.com',
    include: ['#content'],
    exclude: [
      'form',
      '#comments',
      '#paging',
      '.entry-related',
      '.formkit-overlay',
      '.has-small-font-size',
      '.entry-utils',
    ],
  },
  {
    url: '^https?:\\/\\/cloud\\.google\\.com\\/blog\\/',
    include: ['#jump-content', 'c-wiz'],
    exclude: [
      'article-sticky-share-block',
      'article-aspect-image-block',
      'article-cta',
      'related-article-tout-block-external',
      'related-article-tout-block',
      'article-tag-list-block',
      'article-author-block',
      'social-links',
      '.nRhiJb-kR0ZEf-OWXEXe-GV1x9e-ibL1re',
      '.nRhiJb-DbgRPb-c5RTEf-ma6Yeb',
      '.glue-modal',
    ],
  },
  { url: '^https?:\\/\\/medium\\.com\\/$', include: ['article'], exclude: [] },
  {
    url: '^https?:\\/\\/medium\\.com\\/',
    include: ['section', 'main'],
    exclude: ['header', 'footer', 'button'],
  },
  { url: '^https?:\\/\\/([a-zA-Z0-9]+\\.)medium\\.com\\/([^about])', include: ['section'], exclude: [] },
  { url: '^https?:\\/\\/([a-zA-Z0-9]+\\.)medium\\.com\\/about', include: ['main'], exclude: [] },
  { url: '^https?:\\/\\/([a-zA-Z0-9]+\\.)medium\\.com\\/$', include: ['main'], exclude: [] },
  {
    url: '^https?:\\/\\/www\\.wogoo\\.com\\/',
    include: ['.leftSide'],
    exclude: ['.articleComment', '.zan'],
  },
  { url: '^https?:\\/\\/www\\.iocoder\\.cn\\/', include: ['#main'], exclude: ['.article-nav', 'footer'] },
  {
    url: '^https?:\\/\\/help\\.solidworks\\.com\\/',
    include: ['#DSMainContent'],
    exclude: ['#DSLeftPane', '#auto_links'],
  },
  { url: '^https?:\\/\\/effecthouse\\.tiktok\\.com\\/', include: ['section', 'article'], exclude: [] },
];
