name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

# Cancel last CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Runner:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16]
    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --force

      - name: Lint and Types
        run:
          npm run lint
          npm run type:check

      - name: Bundle
        run:
          npm run bundle

